[package]
name = "resolve-products"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
indexmap = "2.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde-enum-str = "0.4.0"
serde_json = "1.0.140"
serde_valid = "1.0.5"

[dev-dependencies]
rstest = "0.25.0"